name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - numpy=2.0.2
  - ase=3.26.0
  - scikit-learn=1.4.2
  - pip=23.3
  - pip:
      - tblite==0.4.0
      - ase-gpatom==1.0.0
      - fairchem-core==2.17.0
