name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - numpy=1.26.4
  - ase=3.22.1
  - scikit-optimize=0.9.0
  - scikit-learn=1.4.2
  - scipy=1.11.4
  - wulffpack=1.5
  - matplotlib=3.8.4
  - pyscf=2.4.0
  - geometric=1.0.2
  - libxc
  - mkl=2024.0
  - mkl-devel=2024.0
  - pip=23.3
  - pip:
      - aalto-boss==1.14.1
      - tblite==0.4.0
      - ase-gpatom==1.0.0
